import { afterEach, beforeEach, describe, expect, layer } from "@effect/vitest";
import { Effect, FileSystem, Path } from "effect";
import { NodeServices } from "@effect/platform-node";
import { fileURLToPath } from "node:url";

import { loadConfig } from "signalgraph/loadConfig";
import { loadSchema } from "signalgraph/loadSchema";
import { generateClient } from "signalgraph/generateClient";

const readGenerated = Effect.fn(function* (out: string) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  return yield* fs.readFileString(path.join(out, "index.ts"));
});

const setupFixture = Effect.fn(function* (fixture: string) {
  const fs = yield* FileSystem.FileSystem;

  const configPath = new URL(`./fixtures/${fixture}/signalgraph.config.ts`, import.meta.url);

  const config = yield* loadConfig(fileURLToPath(configPath));
  const schema = yield* loadSchema(config.schema);

  const out = yield* fs.makeTempDirectory();

  config.out = out;

  yield* generateClient(config, schema);

  return out;
});

const fixture = (name: string) => {
  let out = "";

  beforeEach(() => Effect.gen(function* () {
    out = yield* setupFixture(name).pipe(Effect.provide(NodeServices.layer));
  }).pipe(Effect.runPromise)
  );

  afterEach(() =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      yield* fs.remove(out, { recursive: true });
    }).pipe(Effect.provide(NodeServices.layer), Effect.runPromise)
  );

  return () => out;
};

layer(NodeServices.layer)("generateClient", (it) => {
  describe("files", () => {
    const getOut = fixture("basic");

    it.effect("writes index.ts", () =>
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const exists = yield* fs.exists(path.join(getOut(), "index.ts"));
        expect(exists).toBe(true);
      })
    );

    it.effect("writes generated header", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("// This file was generated by SignalGraph\n// Do not edit this file directly");
      })
    );
  });

  describe("messages", () => {
    const getOut = fixture("basic");

    it.effect("generates payload aliases", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain('type OrdersCreatedPayload = { readonly "orderId": string }');
      })
    );

    it.effect("generates publish methods", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("publish(payload: OrdersCreatedPayload) {");
      })
    );

    it.effect("generates routing table", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain('const routing = {\n  ordersCreated: ["billing"]');
      })
    );
  });

  describe("consumers", () => {
    const getOut = fixture("basic");

    it.effect("generates handle methods", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("handle(handler: (ctx: {\n      payload: OrdersCreatedPayload\n    }) => void");
      })
    );

    it.effect("exports client", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("export const client =");
      })
    );
  });

  describe("inline messages", () => {
    const getOut = fixture("inline");

    it.effect("generates payload aliases", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain('type OrdersCreatedPayload = { readonly "orderId": string }');
      })
    );

    it.effect("generates publish methods", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("publish(payload: OrdersCreatedPayload) {");
      })
    );

    it.effect("generates handle methods", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("handle(handler: (ctx: {\n      payload: OrdersCreatedPayload\n    }) => void");
      })
    );

    it.effect("exports client", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("export const client =");
      })
    );
  });

  describe("duplicate messages", () => {
    const getOut = fixture("duplicate");

    it.effect("emits one payload alias", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content.match(/type OrdersCreatedPayload/g)).toHaveLength(1);
      })
    );

    it.effect("emits one publish method", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content.match(/ordersCreated: {/g)).toHaveLength(1);
      })
    );

    it.effect("routes to every consumer", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain('const routing = {\n  ordersCreated: ["analytics","billing","inventory"]');
      })
    );

    it.effect("generates handle method for each consumer", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("billing: {\n    handle(handler: (ctx: {\n      payload: OrdersCreatedPayload\n    }) => void");
        expect(content).toContain("analytics: {\n    handle(handler: (ctx: {\n      payload: OrdersCreatedPayload\n    }) => void");
        expect(content).toContain("inventory: {\n    handle(handler: (ctx: {\n      payload: OrdersCreatedPayload\n    }) => void");
      })
    );
  });
});
