import { fileURLToPath } from "node:url";

import { NodeServices } from "@effect/platform-node";
import { afterEach, beforeEach, describe, expect, layer } from "@effect/vitest";
import { Effect, FileSystem, Path } from "effect";
import { generateClient } from "signalgraph/generateClient";
import { loadConfig } from "signalgraph/loadConfig";
import { loadSchema } from "signalgraph/loadSchema";

const readGenerated = Effect.fn(function* (out: string) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  return yield* fs.readFileString(path.join(out, "index.ts"));
});

const setupFixture = Effect.fn(function* (fixture: string) {
  const fs = yield* FileSystem.FileSystem;

  const configPath = new URL(`./fixtures/${fixture}/signalgraph.config.ts`, import.meta.url);

  const config = yield* loadConfig(fileURLToPath(configPath));
  const schema = yield* loadSchema(config.schema);

  const out = yield* fs.makeTempDirectory();

  config.out = out;

  yield* generateClient(config, schema);

  return out;
});

const fixture = (name: string) => {
  let out = "";

  beforeEach(() =>
    Effect.gen(function* () {
      out = yield* setupFixture(name).pipe(Effect.provide(NodeServices.layer));
    }).pipe(Effect.runPromise),
  );

  afterEach(() =>
    Effect.gen(function* () {
      const fs = yield* FileSystem.FileSystem;
      yield* fs.remove(out, { recursive: true });
    }).pipe(Effect.provide(NodeServices.layer), Effect.runPromise),
  );

  return () => out;
};

layer(NodeServices.layer)("generateClient", (it) => {
  describe("files", () => {
    const getOut = fixture("basic");

    it.effect("writes index.ts", () =>
      Effect.gen(function* () {
        const fs = yield* FileSystem.FileSystem;
        const path = yield* Path.Path;
        const exists = yield* fs.exists(path.join(getOut(), "index.ts"));
        expect(exists).toBe(true);
      }),
    );

    it.effect("writes generated header", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain(
          "// This file was generated by SignalGraph\n// Do not edit this file directly",
        );
      }),
    );
  });

  describe("imports", () => {
    const getOut = fixture("basic");

    it.effect("imports runtime APIs", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain(
          "import { type RuntimeConsumer, type RuntimeMessage, type MessageGraph, type RuntimeClient, createClient }",
        );
      }),
    );
  });

  describe("payloads", () => {
    const getOut = fixture("basic");

    it.effect("generates payload aliases", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("export type OrdersCreatedPayload");
      }),
    );
  });

  describe("client type", () => {
    const getOut = fixture("basic");

    it.effect("exports Client", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("export type Client =\n  RuntimeClient");
      }),
    );

    it.effect("generates message entries", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("ordersCreated: RuntimeMessage<OrdersCreatedPayload>");
      }),
    );

    it.effect("generates consumer entries", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("billing: RuntimeConsumer<OrdersCreatedPayload>");
      }),
    );

    it.effect("creates runtime client", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("export const Client = createClient<Client>(messageGraph)");
      }),
    );
  });

  describe("routing", () => {
    const getOut = fixture("duplicate");

    it.effect("generates message graph", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("const messageGraph = {\n");
      }),
    );

    it.effect("uses runtime Routing type", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("} satisfies MessageGraph;");
      }),
    );
  });

  describe("duplicate messages", () => {
    const getOut = fixture("duplicate");

    it.effect("emits one payload alias", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content.match(/export type OrdersCreatedPayload/g)).toHaveLength(1);
      }),
    );

    it.effect("emits one message entry", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content.match(/ordersCreated: RuntimeMessage<OrdersCreatedPayload>/g)).toHaveLength(
          1,
        );
      }),
    );

    it.effect("emits one routing entry", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content.match(/"orders.created": \{/g)).toHaveLength(1);
      }),
    );

    it.effect("generates every consumer entry", () =>
      Effect.gen(function* () {
        const content = yield* readGenerated(getOut());
        expect(content).toContain("analytics: RuntimeConsumer<OrdersCreatedPayload>");
        expect(content).toContain("billing: RuntimeConsumer<OrdersCreatedPayload>");
        expect(content).toContain("inventory: RuntimeConsumer<OrdersCreatedPayload>");
      }),
    );
  });
});
