// This file was generated by SignalGraph
// Do not edit this file directly

import {
  type RuntimeConsumer,
  type RuntimeMessage,
  type MessageGraph,
  type RuntimeClient,
  createClient,
} from "@signalgraph/runtime";

import { OrderCreated, OrderCompleted, Analytics, Billing, Shipping } from "./schema.ts";

export type OrderCreatedPayload = { readonly orderId: number };

export type OrderCompletedPayload = { readonly orderId: number };

export type Client = RuntimeClient & {
  orderCreated: RuntimeMessage<OrderCreatedPayload>;
  orderCompleted: RuntimeMessage<OrderCompletedPayload>;
  analytics: RuntimeConsumer<OrderCreatedPayload>;
  billing: RuntimeConsumer<OrderCreatedPayload>;
  shipping: RuntimeConsumer<OrderCompletedPayload>;
};

const messageGraph = {
  "order.created": {
    definition: OrderCreated,
    consumers: [Analytics, Billing],
  },
  "order.completed": {
    definition: OrderCompleted,
    consumers: [Shipping],
  },
} satisfies MessageGraph;

export const Client = createClient<Client>(messageGraph);
