import { Effect, FileSystem, Path, SchemaRepresentation } from "effect";
import type { SchemaData } from "./loadSchema.ts";
import type { Config } from "./config.ts";
import type { AnyMessage, MessageSchema } from "./message.ts";
import type { Consumer } from "./consumer.ts";

const toCamelCase = (text: string) =>
  text
    .split(".")
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");

const toPascalCase = (text: string) =>
  text.split(".")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");

const indent = (text: string, spaces = 2) =>
  text
    .split("\n")
    .map((line) => " ".repeat(spaces) + line)
    .join("\n");

function generateSchemaType(schema: MessageSchema) {
  const document = SchemaRepresentation.fromAST(schema.ast);
  const multi = SchemaRepresentation.toMultiDocument(document);
  const code = SchemaRepresentation.toCodeDocument(multi);

  return code.codes[0].Type;
};

function generateMessageEntries(messages: Iterable<AnyMessage>) {
  return [...messages].map(
    (message) => `${toCamelCase(message.name)}: Message<${toPascalCase(message.name)}Payload>;`
  );
}

function generateConsumerEntries(consumers: Iterable<Consumer<string, AnyMessage>>) {
  return [...consumers].map(
    (consumer) => `${toCamelCase(consumer.name)}: Consumer<${toPascalCase(consumer.message.name)}Payload>;`
  );
}

function generateTypeAliases(messages: Iterable<AnyMessage>) {
  return [...messages].map(
    (message) =>
      `export type ${toPascalCase(message.name)}Payload = ${generateSchemaType(message.schema)}`
  );
}

function generateMessageGraph(data: SchemaData) {
  return [...data.messages.values()].map((message) => {
    const exportName = data.messageExportNames.get(message.name);
    const consumerNames = [...data.consumers.values()]
      .filter((consumer) => consumer.message.name === message.name)
      .map((consumer) => `"${consumer.name}"`)
      .join(", ");
    return `"${message.name}": {
  definition: ${exportName},
  consumers: [${consumerNames}]
}`;
  });
}

export const generateClient = Effect.fn(function* (config: Config, data: SchemaData) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const outputPath = config.out + "/index.ts";
  const outputDir = path.dirname(outputPath);
  yield* fs.makeDirectory(outputDir, { recursive: true });

  const header = `// This file was generated by SignalGraph
// Do not edit this file directly`;

  const entries = [
    ...generateMessageEntries(data.messages.values()),
    ...generateConsumerEntries(data.consumers.values())
  ];

  let schemaRelativePath = path.relative(outputDir, config.schema);
  if (!schemaRelativePath.startsWith(".")) {
    schemaRelativePath = "./" + schemaRelativePath;
  }
  const schemaExportNames = [...new Set(data.messageExportNames.values())];
  const schemaImport =
    schemaExportNames.length > 0
      ? `import {\n${indent(schemaExportNames.join(",\n"))}\n} from "${schemaRelativePath}";`
      : "";

  const imports = [
    'import { Effect } from "effect";',
    'import { type Consumer, type Message, type MessageGraph, createClient } from "@signalgraph/runtime";',
    `import { ${config.broker.layer} } from "${config.broker.package}";`,
    schemaImport
  ]
    .filter(Boolean)
    .join("\n");

  const aliases = generateTypeAliases(data.messages.values()).join("\n\n");

  const client =
    [
      "export type Client = {",
      indent(entries.join("\n")),
      "};"
    ].join("\n");

  const messageGraph =
    [
      "const messageGraph = {",
      indent(generateMessageGraph(data).join(",\n")),
      "} satisfies MessageGraph;"
    ].join("\n");

  const exportClient = `export const makeClient = createClient<Client>(messageGraph).pipe(Effect.provide(${config.broker.layer}));`;

  const source = [
    header,
    imports,
    aliases,
    client,
    messageGraph,
    exportClient
  ].join("\n\n");

  yield* fs.writeFileString(outputPath, source, { flag: "w" });
})
