import { Effect, FileSystem, Path } from "effect";
import type { SchemaData } from "./loadSchema.ts";
import type { Project } from "./findProjectRoot.ts";

const toCamelCase = (name: string) =>
  name
    .split(".")
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");

const indent = (text: string, spaces = 2) =>
  text
    .split("\n")
    .map((line) => " ".repeat(spaces) + line)
    .join("\n");

function generateMessages(messages: SchemaData["messages"]) {
  return messages.map((message) => `
${toCamelCase(message.name)}: {
  publish(payload: never) {
    throw new Error("Not implemented");
  }
}`.trim());
}

function generateConsumers(consumers: SchemaData["consumers"]) {
  return consumers.map((consumer) => `
${toCamelCase(consumer.name)}: {
  handle(handler: never) {
    throw new Error("Not implemented");
  }
}`.trim());
}

export const generateClient = Effect.fn(function* (project: Project, data: SchemaData) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const outputPath = project.root + "/generated/signalgraph/index.ts";
  const outputDir = path.dirname(outputPath);

  yield* fs.makeDirectory(outputDir, { recursive: true });

  const header = `// This file was generated by SignalGraph
// Do not edit this file directly
`;

  const entries = [
    ...generateMessages(data.messages),
    ...generateConsumers(data.consumers)
  ];

  const source = [
    header,
    "export const client = {",
    indent(entries.join(",\n\n")),
    "}"
  ].join("\n");

  yield* fs.writeFileString(outputPath, source, { flag: "w" });
})
