import { Effect, FileSystem, Path, Schema, SchemaRepresentation } from "effect";
import type { SchemaData } from "./loadSchema.ts";
import type { Project } from "./findProjectRoot.ts";

const toCamelCase = (text: string) =>
  text
    .split(".")
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join("");

const toPascalCase = (text: string) =>
  text.split(".")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");

const indent = (text: string, spaces = 2) =>
  text
    .split("\n")
    .map((line) => " ".repeat(spaces) + line)
    .join("\n");

function schemaType(schema: Schema.Decoder<unknown, never>) {
  const document = SchemaRepresentation.fromAST(schema.ast);
  const multi = SchemaRepresentation.toMultiDocument(document);
  const code = SchemaRepresentation.toCodeDocument(multi);

  return code.codes[0].Type;
};

function generateMessages(messages: SchemaData["messages"]) {
  return messages.map((message) => `
${toCamelCase(message.name)}: {
  publish(payload: ${toPascalCase(message.name)}Payload) {
    throw new Error("Not implemented");
  }
}`.trim());
};

function generateConsumers(consumers: SchemaData["consumers"]) {
  return consumers.map((consumer) => `
${toCamelCase(consumer.name)}: {
  handle(handler: (ctx: {
    payload: ${toPascalCase(consumer.message.name)}Payload
  }) => void) {
    throw new Error("Not implemented");
  }
}`.trim());
}

function generateTypeAliases(messages: SchemaData["messages"]) {
  return messages.map((message) => `
type ${toPascalCase(message.name)}Payload = ${schemaType(message.schema)}
`.trim());
}

export const generateClient = Effect.fn(function* (project: Project, data: SchemaData) {
  const fs = yield* FileSystem.FileSystem;
  const path = yield* Path.Path;

  const outputPath = project.root + "/generated/signalgraph/index.ts";
  const outputDir = path.dirname(outputPath);

  yield* fs.makeDirectory(outputDir, { recursive: true });

  const header = `// This file was generated by SignalGraph
// Do not edit this file directly
`;

  const entries = [
    ...generateMessages(data.messages),
    ...generateConsumers(data.consumers)
  ];

  const source = [
    header,
    ...generateTypeAliases(data.messages),
    "\n",
    "export const client = {",
    indent(entries.join(",\n\n")),
    "}"
  ].join("\n");

  yield* fs.writeFileString(outputPath, source, { flag: "w" });
})
